application: nusbridge
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: /fonts
  static_dir: fonts

# Handler for front page
- url: /
  script: nusbridge.app

# All other pages require login
- url: /.*
  script: nusbridge.app
  login: required

libraries:
- name: jinja2
  version: latest